document.writeln("<div class='footer'>");
document.writeln("    <div class='foot'>");
document.writeln("        <div class='menu-list'>");
document.writeln("            <div class='follow' id='follow-qr'>");
document.writeln("                <h3>关注尔克</h3>");
document.writeln("                <a href='' class='qrcode-vx'></a>");
document.writeln("                <div class='qrcode-pic' style='left: -24px;'><i></i><img src='./image/vx.png' /></div>");
document.writeln("                <a href='http://weibo.com/chinahongxing?sudaref=www.so.com&retcode=6102&is_all=1' target='_blank' class='qrcode-wb'></a>");
document.writeln("                <div class='qrcode-pic' style='left: 19px;'><i></i><img src='./image/wb.png' /></div>");
document.writeln("            </div>");
document.writeln("            <div class='menu'>");
document.writeln("                <h3>人才战略</h3>");
document.writeln("                <ul>");
document.writeln("                    <li>");
document.writeln("                        <a href='/rczhl/ygfc/'>员工风采</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href='/rczhl/rczhp/'>人才招聘</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class='menu'>");
document.writeln("                <h3>客户服务</h3>");
document.writeln("                <ul>");
document.writeln("                    <li>");
document.writeln("                        <a href='/khfw/lxwm/'>联系我们</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href='/khfw/fwchx/' target='_blank'>防伪查询</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class='menu'>");
document.writeln("                <h3>商务合作</h3>");
document.writeln("                <ul>");
document.writeln("                    <li>");
document.writeln("                        <a href='/shwhz/tgyw/'>团购业务</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href='/shwhz/jmxx/'>加盟信息</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </div>");
document.writeln("            <div class='clear'></div>");
document.writeln("        </div>");
document.writeln("        <div class='foot-info'>");
document.writeln("            <div class='right-part'>");
document.writeln("                <a>中国</a>© 2017 Erke, Inc. 保留所有权利&nbsp;&nbsp;&nbsp;<a href='https://beian.miit.gov.cn/#/Integrated/index' target='_blank'>闽ICP备05018314号</a>");
document.writeln("            </div>");
document.writeln("            <div class='left-part'>");
document.writeln("                <a href='/khfw/yszhc/'>隐私政策</a>|<a href='http://wx.erke.com/web/wechat/map/index.html' target='_blank'>发现店铺</a>");
document.writeln("");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script>");
document.writeln("window.onload=function(){");
document.writeln(" var oDiv = document.getElementById('follow-qr');");
document.writeln(" var aA = oDiv.getElementsByTagName('a');");
document.writeln(" var aImg =oDiv.getElementsByTagName('div');");
document.writeln("");
document.writeln("    for(var i=0;i<aA.length;i++){");
document.writeln("        aA[i].index = i;");
document.writeln("        aA[i].onmouseover=function(){");
document.writeln("            for(var i=0;i<aA.length;i++){");
document.writeln("                aImg[i].style.display = 'none'");
document.writeln("            }");
document.writeln("            aImg[this.index].style.display = 'block';");
document.writeln("       };");
document.writeln("       aA[i].onmouseout=function(){");
document.writeln("            for(var i=0;i<aA.length;i++){");
document.writeln("                aImg[i].style.display = 'none'");
document.writeln("            }");
document.writeln("       };");
document.writeln("    }");
document.writeln("");
document.writeln("};");
document.writeln("</script>");


