document.writeln("<div class='header'>");
document.writeln("    <div class='top-part'>");
document.writeln("        <a href=''>");
document.writeln("            <img src='./image/langues.jpg' />");
document.writeln("        </a>");
document.writeln("        <a class='a-cart' href=''>");
// document.writeln("            <img src='/images/cart.png' />");
// document.writeln("        </a>");
// document.writeln("        <a href='./注册.html'>免费注册</a>");
// document.writeln("        <a href='./登录.html'>登录</a>");
document.writeln("        <span>欢迎来到鸿星尔克！</span>");
document.writeln("    </div>");
document.writeln("    <div class='bottom-part'>");
document.writeln("        <a class='logo' href='/'>");
document.writeln("            <img src='./image/logo.png' />");
document.writeln("        </a>");
document.writeln("        <div style='z-index:100;' class='search-form'>");
document.writeln("        <form id='form1' name='form1' action='/ss/' target='_blank' >");
document.writeln("            <button type='submit'></button>");
document.writeln("            <input name='q' id='q' type='text' value='' placeholder='搜索' />");
document.writeln("            <input name='esiteid' type='hidden' value='216' />");
document.writeln("            <input name='indexid' type='hidden' value='21' />");
document.writeln("        </form>");
document.writeln("        </div>");
document.writeln("        <div class='nav'>");
document.writeln("            <ul>");
document.writeln("            <div class='lavalamp-object'></div>");
document.writeln("                <li class='has-next-nav'>");
document.writeln("                    <a href='/'>首页</a>");
document.writeln("                </li>");
document.writeln("                <li class='has-next-nav'>");
document.writeln("                    <a>尔克产品</a>");
document.writeln("                </li>");
document.writeln("                <li class='has-next-nav'>");
document.writeln("                    <a>新闻中心</a>");
document.writeln("                </li>");
document.writeln("                <li class='has-next-nav'>");
document.writeln("                    <a href='./商城.html' target='_blank'>线上商城</a>");
document.writeln("                </li>");
document.writeln("                <li class='has-next-nav'>");
document.writeln("                    <a>关于ERKE</a>");
document.writeln("                </li>");
document.writeln("                <li class='has-next-nav'>");
document.writeln("                    <a href='http://en.erke.com/'  target='_blank'>ERKE海外</a>");
document.writeln("                </li>");
document.writeln("                <li class='has-next-nav'>");
document.writeln("                    <a href='http://vip.erke.com/'  target='_blank'>会员联盟</a>");
document.writeln("                </li>");
document.writeln("                <li class='has-next-nav'>");
document.writeln("                    <a>互动留言</a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        <div class='sub-nav'>");
document.writeln("            <div class='nav-next nav-next2'>0");
document.writeln("            </div>");
document.writeln("            <div class='nav-next'>");
document.writeln("                <div class='box-nav'>");
document.writeln("                <div class='ad'>");
document.writeln("                    <a href=''>");
document.writeln("                        <img src='./image/sy_ad.jpg' />");
document.writeln("                    </a>");
document.writeln("                </div>");
document.writeln("                <div class='part'>");
document.writeln("                    <h3>");
document.writeln("                        <a href='/ekchp/nf/'>男装</a>");
document.writeln("                    </h3>");
document.writeln("                    <ul>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nf/pb/'>跑步</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nf/zx/'>综训</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nf/hw/'>户外</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nf/wq/'>网球</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nf/dq/'>大球</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nf/shh/'>生活</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class='part'>");
document.writeln("                    <h3>");
document.writeln("                        <a href='/ekchp/nvf/'>女装</a>");
document.writeln("                    </h3>");
document.writeln("                    <ul>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nvf/pb/'>跑步</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nvf/zx/'>综训</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nvf/hw/'>户外</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nvf/wq/'>网球</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nvf/dq/'>大球</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nvf/shh/'>生活</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class='part'>");
document.writeln("                    <h3>");
document.writeln("                        <a href='/ekchp/nx/'>男鞋</a>");
document.writeln("                    </h3>");
document.writeln("                    <ul>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nx/pb/'>跑步</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nx/zx/'>综训</a>");
document.writeln("                        </li>");
//document.writeln("                        <li>");
//document.writeln("                            <a href='/ekchp/nx/wq/'>网球</a>");
//document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nx/lq/'>篮球</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nx/hb/'>滑板</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nx/mp/'>慢跑</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class='part'>");
document.writeln("                    <h3>");
document.writeln("                        <a href='/ekchp/nvx/'>女鞋</a>");
document.writeln("                    </h3>");
document.writeln("                    <ul>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nvx/pb/'>跑步</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nvx/zx/'>综训</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nvx/mp/'>慢跑</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/nvx/hb/'>滑板</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class='part'>");
document.writeln("                    <h3>");
document.writeln("                        <a>配件</a>");
document.writeln("                    </h3>");
document.writeln("                    <ul>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/pj/b/'>包</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/pj/ny/'>内衣</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/pj/wz/'>袜子</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/pj/mz/'>帽子</a>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a href='/ekchp/pj/ql/'>球</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");
document.writeln("                </div>");
document.writeln("                <div class='clear'></div>");
document.writeln("            </div>");
document.writeln("            </div>");
document.writeln("            <div class='nav-next nav-next2'>");
document.writeln("                <div class='nav-next-box'>");
document.writeln("                    <div class='box-nav box-nav2'>");
document.writeln("                       <a href='/xwzx/qyxw/'>企业新闻</a>");
document.writeln("                       <a href='/xwzx/ppxw/'>品牌新闻</a>");
document.writeln("                       <a href='/xwzx/wqzht/'>网球专题</a>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class='nav-next nav-next2'>3");
document.writeln("            </div>");
document.writeln("            <div class='nav-next nav-next2'>");
document.writeln("            	<div class='nav-next-box'>");
document.writeln("                    <div class='box-nav box-nav2'>");
document.writeln("                       <a href='/gyERKE/qyjsh/'>企业介绍</a>");
document.writeln("                       <a href='/gyERKE/ppshy/'>品牌释义</a>");
document.writeln("                       <a href='/gyERKE/qywh/'>企业文化</a>");
document.writeln("                       <a href='/gyERKE/fzhlch/'>发展历程</a>");
document.writeln("                       <a href='/gyERKE/shhzr/'>社会责任</a>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class='nav-next nav-next2'>5");
document.writeln("            </div>");
document.writeln("            <div class='nav-next nav-next2'>6");
document.writeln("            </div>");
document.writeln("            <div class='nav-next nav-next2'>");
document.writeln("            	<div class='nav-next-box'>");
document.writeln("                    <div class='box-nav box-nav2'>");
document.writeln("                       <a href='/hdly/zxly/'>在线留言</a>");
document.writeln("                       <a href='/hdly/dchwj/'>调查问卷</a>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("<div style='height:50px;background:#fff;'></div>");
document.writeln("</div>");
document.writeln("");





